/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExprandExpression extends PExpression
{
    private PExpression _expression_;
    private TOr _or_;
    private PExpression1 _expression1_;

    public AExprandExpression()
    {
        // Constructor
    }

    public AExprandExpression(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PExpression1 _expression1_)
    {
        // Constructor
        setExpression(_expression_);

        setOr(_or_);

        setExpression1(_expression1_);

    }

    @Override
    public Object clone()
    {
        return new AExprandExpression(
            cloneNode(this._expression_),
            cloneNode(this._or_),
            cloneNode(this._expression1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprandExpression(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PExpression1 getExpression1()
    {
        return this._expression1_;
    }

    public void setExpression1(PExpression1 node)
    {
        if(this._expression1_ != null)
        {
            this._expression1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._or_)
            + toString(this._expression1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._expression1_ == child)
        {
            this._expression1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._expression1_ == oldChild)
        {
            setExpression1((PExpression1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
