/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExprExpressionList extends PExpressionList
{
    private PExpression _expression_;
    private PExpressionListBis _expressionListBis_;

    public AExprExpressionList()
    {
        // Constructor
    }

    public AExprExpressionList(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") PExpressionListBis _expressionListBis_)
    {
        // Constructor
        setExpression(_expression_);

        setExpressionListBis(_expressionListBis_);

    }

    @Override
    public Object clone()
    {
        return new AExprExpressionList(
            cloneNode(this._expression_),
            cloneNode(this._expressionListBis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprExpressionList(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public PExpressionListBis getExpressionListBis()
    {
        return this._expressionListBis_;
    }

    public void setExpressionListBis(PExpressionListBis node)
    {
        if(this._expressionListBis_ != null)
        {
            this._expressionListBis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionListBis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._expressionListBis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._expressionListBis_ == child)
        {
            this._expressionListBis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._expressionListBis_ == oldChild)
        {
            setExpressionListBis((PExpressionListBis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
