/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExprorExpression1 extends PExpression1
{
    private PExpression1 _expression1_;
    private TAnd _and_;
    private PExpression2 _expression2_;

    public AExprorExpression1()
    {
        // Constructor
    }

    public AExprorExpression1(
        @SuppressWarnings("hiding") PExpression1 _expression1_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PExpression2 _expression2_)
    {
        // Constructor
        setExpression1(_expression1_);

        setAnd(_and_);

        setExpression2(_expression2_);

    }

    @Override
    public Object clone()
    {
        return new AExprorExpression1(
            cloneNode(this._expression1_),
            cloneNode(this._and_),
            cloneNode(this._expression2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprorExpression1(this);
    }

    public PExpression1 getExpression1()
    {
        return this._expression1_;
    }

    public void setExpression1(PExpression1 node)
    {
        if(this._expression1_ != null)
        {
            this._expression1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression1_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PExpression2 getExpression2()
    {
        return this._expression2_;
    }

    public void setExpression2(PExpression2 node)
    {
        if(this._expression2_ != null)
        {
            this._expression2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression1_)
            + toString(this._and_)
            + toString(this._expression2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression1_ == child)
        {
            this._expression1_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._expression2_ == child)
        {
            this._expression2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression1_ == oldChild)
        {
            setExpression1((PExpression1) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._expression2_ == oldChild)
        {
            setExpression2((PExpression2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
