/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AFunctionCallInstruction extends PInstruction
{
    private PFunctionCallInstruction _functionCallInstruction_;

    public AFunctionCallInstruction()
    {
        // Constructor
    }

    public AFunctionCallInstruction(
        @SuppressWarnings("hiding") PFunctionCallInstruction _functionCallInstruction_)
    {
        // Constructor
        setFunctionCallInstruction(_functionCallInstruction_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionCallInstruction(
            cloneNode(this._functionCallInstruction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionCallInstruction(this);
    }

    public PFunctionCallInstruction getFunctionCallInstruction()
    {
        return this._functionCallInstruction_;
    }

    public void setFunctionCallInstruction(PFunctionCallInstruction node)
    {
        if(this._functionCallInstruction_ != null)
        {
            this._functionCallInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionCallInstruction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionCallInstruction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionCallInstruction_ == child)
        {
            this._functionCallInstruction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionCallInstruction_ == oldChild)
        {
            setFunctionCallInstruction((PFunctionCallInstruction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
