/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AInstructionInstructionList extends PInstructionList
{
    private PInstruction _instruction_;
    private PInstructionListBis _instructionListBis_;

    public AInstructionInstructionList()
    {
        // Constructor
    }

    public AInstructionInstructionList(
        @SuppressWarnings("hiding") PInstruction _instruction_,
        @SuppressWarnings("hiding") PInstructionListBis _instructionListBis_)
    {
        // Constructor
        setInstruction(_instruction_);

        setInstructionListBis(_instructionListBis_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionInstructionList(
            cloneNode(this._instruction_),
            cloneNode(this._instructionListBis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionInstructionList(this);
    }

    public PInstruction getInstruction()
    {
        return this._instruction_;
    }

    public void setInstruction(PInstruction node)
    {
        if(this._instruction_ != null)
        {
            this._instruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instruction_ = node;
    }

    public PInstructionListBis getInstructionListBis()
    {
        return this._instructionListBis_;
    }

    public void setInstructionListBis(PInstructionListBis node)
    {
        if(this._instructionListBis_ != null)
        {
            this._instructionListBis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionListBis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instruction_)
            + toString(this._instructionListBis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instruction_ == child)
        {
            this._instruction_ = null;
            return;
        }

        if(this._instructionListBis_ == child)
        {
            this._instructionListBis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instruction_ == oldChild)
        {
            setInstruction((PInstruction) newChild);
            return;
        }

        if(this._instructionListBis_ == oldChild)
        {
            setInstructionListBis((PInstructionListBis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
