/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AInstructionInstructionListBis extends PInstructionListBis
{
    private PInstructionListBis _instructionListBis_;

    public AInstructionInstructionListBis()
    {
        // Constructor
    }

    public AInstructionInstructionListBis(
        @SuppressWarnings("hiding") PInstructionListBis _instructionListBis_)
    {
        // Constructor
        setInstructionListBis(_instructionListBis_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionInstructionListBis(
            cloneNode(this._instructionListBis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionInstructionListBis(this);
    }

    public PInstructionListBis getInstructionListBis()
    {
        return this._instructionListBis_;
    }

    public void setInstructionListBis(PInstructionListBis node)
    {
        if(this._instructionListBis_ != null)
        {
            this._instructionListBis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionListBis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructionListBis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructionListBis_ == child)
        {
            this._instructionListBis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructionListBis_ == oldChild)
        {
            setInstructionListBis((PInstructionListBis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
