/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AProgramProgram extends PProgram
{
    private POptionalVariableDeclarationList _optionalVariableDeclarationList_;
    private PFunctionDeclarationList _functionDeclarationList_;

    public AProgramProgram()
    {
        // Constructor
    }

    public AProgramProgram(
        @SuppressWarnings("hiding") POptionalVariableDeclarationList _optionalVariableDeclarationList_,
        @SuppressWarnings("hiding") PFunctionDeclarationList _functionDeclarationList_)
    {
        // Constructor
        setOptionalVariableDeclarationList(_optionalVariableDeclarationList_);

        setFunctionDeclarationList(_functionDeclarationList_);

    }

    @Override
    public Object clone()
    {
        return new AProgramProgram(
            cloneNode(this._optionalVariableDeclarationList_),
            cloneNode(this._functionDeclarationList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramProgram(this);
    }

    public POptionalVariableDeclarationList getOptionalVariableDeclarationList()
    {
        return this._optionalVariableDeclarationList_;
    }

    public void setOptionalVariableDeclarationList(POptionalVariableDeclarationList node)
    {
        if(this._optionalVariableDeclarationList_ != null)
        {
            this._optionalVariableDeclarationList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optionalVariableDeclarationList_ = node;
    }

    public PFunctionDeclarationList getFunctionDeclarationList()
    {
        return this._functionDeclarationList_;
    }

    public void setFunctionDeclarationList(PFunctionDeclarationList node)
    {
        if(this._functionDeclarationList_ != null)
        {
            this._functionDeclarationList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionDeclarationList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optionalVariableDeclarationList_)
            + toString(this._functionDeclarationList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optionalVariableDeclarationList_ == child)
        {
            this._optionalVariableDeclarationList_ = null;
            return;
        }

        if(this._functionDeclarationList_ == child)
        {
            this._functionDeclarationList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optionalVariableDeclarationList_ == oldChild)
        {
            setOptionalVariableDeclarationList((POptionalVariableDeclarationList) newChild);
            return;
        }

        if(this._functionDeclarationList_ == oldChild)
        {
            setFunctionDeclarationList((PFunctionDeclarationList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
