/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AReadInstruction extends PInstruction
{
    private PReadInstruction _readInstruction_;

    public AReadInstruction()
    {
        // Constructor
    }

    public AReadInstruction(
        @SuppressWarnings("hiding") PReadInstruction _readInstruction_)
    {
        // Constructor
        setReadInstruction(_readInstruction_);

    }

    @Override
    public Object clone()
    {
        return new AReadInstruction(
            cloneNode(this._readInstruction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReadInstruction(this);
    }

    public PReadInstruction getReadInstruction()
    {
        return this._readInstruction_;
    }

    public void setReadInstruction(PReadInstruction node)
    {
        if(this._readInstruction_ != null)
        {
            this._readInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._readInstruction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._readInstruction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._readInstruction_ == child)
        {
            this._readInstruction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._readInstruction_ == oldChild)
        {
            setReadInstruction((PReadInstruction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
