/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AReturnInstruction extends PInstruction
{
    private PReturnInstruction _returnInstruction_;

    public AReturnInstruction()
    {
        // Constructor
    }

    public AReturnInstruction(
        @SuppressWarnings("hiding") PReturnInstruction _returnInstruction_)
    {
        // Constructor
        setReturnInstruction(_returnInstruction_);

    }

    @Override
    public Object clone()
    {
        return new AReturnInstruction(
            cloneNode(this._returnInstruction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReturnInstruction(this);
    }

    public PReturnInstruction getReturnInstruction()
    {
        return this._returnInstruction_;
    }

    public void setReturnInstruction(PReturnInstruction node)
    {
        if(this._returnInstruction_ != null)
        {
            this._returnInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._returnInstruction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._returnInstruction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._returnInstruction_ == child)
        {
            this._returnInstruction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._returnInstruction_ == oldChild)
        {
            setReturnInstruction((PReturnInstruction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
