/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AWhileInstruction extends PInstruction
{
    private PWhileInstruction _whileInstruction_;

    public AWhileInstruction()
    {
        // Constructor
    }

    public AWhileInstruction(
        @SuppressWarnings("hiding") PWhileInstruction _whileInstruction_)
    {
        // Constructor
        setWhileInstruction(_whileInstruction_);

    }

    @Override
    public Object clone()
    {
        return new AWhileInstruction(
            cloneNode(this._whileInstruction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileInstruction(this);
    }

    public PWhileInstruction getWhileInstruction()
    {
        return this._whileInstruction_;
    }

    public void setWhileInstruction(PWhileInstruction node)
    {
        if(this._whileInstruction_ != null)
        {
            this._whileInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileInstruction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileInstruction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileInstruction_ == child)
        {
            this._whileInstruction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileInstruction_ == oldChild)
        {
            setWhileInstruction((PWhileInstruction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
